#page title
page_title                                : KONEX                                     # Automatically populates with business name if not set and if iOS business ID is set. Otherwise enter manually.

# business Info
business_id                                : 1234793120                                # Required. Enter iOS business ID to automatically populate name, price and icons (e.g. 718043190).
business_country                           : ht                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

business_whatsapp_link                    : https://wa.me/50932716969?text=Mwen%20enterese%20nan%20Konex 
business_telegram_link                    : https://t.me/konexht                      # Automatically populates if not set and if iOS business ID is set. Otherwise enter manually.
presskit_download_link                    :                                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

business_icon                                  : assets/konexlogo.png                      # Automatically populates if not set and if iOS business ID is set.  Otherwise enter path to icon file manually.
business_name                                  : MANDE YON SÈVIS                                         # Automatically populates if not set and if iOS business ID is set.  Otherwise enter manually.
business_price                                 :                                         # Automatically populates if not set and if iOS business ID is set.  Otherwise enter manually.
business_description                           : 

enable_smart_business_banner                   : true                                      # Set to true to show a smart business banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Konex                               
your_link                                 : https://konexht.github.io/                   
your_city                                 : Gonaives                                
email_address                             : services.konex@gmail.com
whatsapp_link                             : 50932716969
facebook_username                         : https://facebook.com/konexht                                          
instagram_username                        : konexht
tiktok_username                           : konexht
twitter_username                          : konexht
github_username                           : 
youtube_username                          : 



# service List                            Edit, add or remove services to be presented.
services                                  :

  - title                                 : Konsiltasyon enfòmatik 
    description                           : Kote w ye, nou la pou ou. Nou rapid e sèvis nou yo de kalite. Sa w ap tann pou w kontakte n?
    fontawesome_icon_name                 : magic

  - title                                 : Fòmasyon a distans
    description                           : Nou gen fòmasyon teknik ki ka itil ou pou w kreye yon sèvis pou tèt ou ak pou biznis ou.
    fontawesome_icon_name                 : mobile

  - title                                 : Pwogramasyon telefòn 
    description                           : Nou ofri telefòn ki tou pare pou biznis, 100% sèvis otomatize. Yo ka reponn mesaj SMS ak Telegram poukont yo epi fè swivi pou ou tankou se yon anplwaye ou genyen.
    fontawesome_icon_name                 : play-circle

  - title                                 : Sekirite 
    description                           : Malè rive sanzatann, nou ka ba w zouti dijital pou sizoka ou menm oswa yon manm fanmi w ta twouve l an difikilte.
    fontawesome_icon_name                 : user-lock

  - title                                 : Edikasyon
    description                           : Nou sèvi ak bonjan teknoloji pou ede paran, elèv ak pwofesè gen aksè ak resous pedagojik san distraksyon.
    fontawesome_icon_name                 : adjust

  - title                                 : Konsepsyon grafik
    description                           : Ou renmen bèl imaj byen prezante sou divès kalite fòma. Nou vle pou w satisfè lè w mande nou yon konsepsyon grafik.
    fontawesome_icon_name                 : star

  - title                                 : Kreyasyon ak trètman tèks
    description                           : Depi se tèks, sou prèske tout sijè, nou ka ede w kreye l, trete l, korije l epi tradui l. Brèf, lage l nan men nou e ou p ap regrèt sa!
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Asistans pou ranpli dosye
    description                           : Keseswa fòmilè pou anbasad oswa aplikasyon pou yon admisyon inivèsite nan peyi etranje, nap akonpaye w jiskobou.
    fontawesome_icon_name                 : link

  - title                                 : Ak anpil lòt ankò
    description                           : Jis fè nou konnen e n ap fè kè w kontan
    fontawesome_icon_name                 : info-circle

  - title                                 : # New service Title
    description                           : # New service Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

business_title_color                           : "#ffffff"
business_price_color                           : "#ffffff"
business_description_color                     : "#ffffff"

service_title_color                       : "#000000"
service_text_color                        : "#666666"

service_icons_foreground_color            : "#1d63ea"
service_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
